apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-game
  labels:
    app: web-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rock-paper-scissors
  template:
    metadata:
      labels:
        app: rock-paper-scissors
    spec:
      containers:
      - name: rps
        image: public.ecr.aws/b2c8i7x6/rock-paper-scissors:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred

