---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: monitoring
  name: targets
  labels:
    prometheus: main
spec:
  group:
    - name: targets
      rules:
        - alert: PrometheusTargetsMissing
          expr: up == 0
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: Prometheus target missing (instance {{ $labels.instance }})
            description: "A Prometheus target has disappeared. An exporter might be crashed.\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"