---
- hosts: remote_servers
  become: yes
  tasks:
    - name: Stop and remove Docker Compose containers and services
      docker_compose:
        state: absent
        project_src: /opt/app/
    - name: Remove Docker Compose files
      file:
        path: /opt/app/docker-compose.yml
        state: absent
    # - name: Remove Docker images
    #   docker_image:
    #     name: "{{ item }}"
    #     state: absent
    #   loop:
    #     - nginx
    #     - php
    #     - mysql
    #     - app_app-data
    #     - app_nginx
    #     - app_php
    #     - app_mysql
    - name: Remove Dockerfiles directories
      file:
        path: "/opt/app/Dockerfiles/{{ item }}"
        state: directory
      loop:
        - nginx
        - php
        - mysql
    - name: Remove www directory
      file:
        path: /opt/app/www/
        state: directory